### ISSUE TITLE
Integrations from Infisical to Platform X

### ISSUE THREAD

**Issue by dangtony98** [Infisical/infisical#673]
### Feature description
One of the things that makes Infisical special is its native integrations with platforms like Vercel, Netlify, GitHub, GitLab, Render, etc.

For those of you new to Infisical, an integration from Infisical to anther platform involves sending secrets/environment variables from Infisical to that platform; this is typically done by referencing that platform's API and making API calls containing the secrets from Infisical to that platform.

Below is a list of **needed** integrations:
- [x] Laravel Forge #672
- [x] Codefresh #671 
- [x] DigitalOcean Apps #732
- [x] Qovery #669
- [x] Terraform Cloud #668
- [x] Windmill #679
- [x] BitBucket #710
- [ ] Azure App Service #502 
- [x] Cloudflare Workers #1151 
- [x] Northflank #652
- [x] TeamCity #646
- [ ] Cirrus CI #417 
- [ ] Harness.io #301 (underway)
- [ ] Scaleway #395 (underway)
- [x] Cloud 66 #388
- [x] GCP Secret Manager #285 (underway)

### Why would it be useful?
These integrations would make possible users of those platforms to store their secrets/environment variables with Infisical.

### Additional context
Building an integration between Infisical and another platform is quite simple and can be split into 2 categories:
- Those involving creating an API token/key in the other platform and passing that to Infisical (e.g. Render, Fly.io, Railway integrations).
- Those involving granting Infisical access to the other platform via OAuth2 (e.g. Vercel, GitHub, Gitlab integrations).

In both cases, there are plenty of examples in the codebase to go off of but to list out common items that need to be completed to setup a new integration:

1. Adding integration URL variables [here](https://github.com/Infisical/infisical/blob/main/backend/src/variables/integration.ts).
2. Adding integration names to the database model schemas [here](https://github.com/Infisical/infisical/blob/main/backend/src/models/integrationAuth.ts) and [here](https://github.com/Infisical/infisical/blob/main/backend/src/models/integration.ts).
3. Adding window redirects to integration authorization/creation pages [here](https://github.com/Infisical/infisical/blob/main/frontend/src/pages/integrations/%5Bid%5D.tsx); you need to create those pages in `frontend/src/pages/integrations`.
4. Filling out `apps.ts` for your integration to get apps for that integration [here](https://github.com/Infisical/infisical/blob/main/backend/src/integrations/apps.ts).
5. Filling out `sync.ts` for your integration to sync secrets from Infisical to that integration [here](https://github.com/Infisical/infisical/blob/main/backend/src/integrations/sync.ts).
6. *** If you're working on an OAuth2 integration, then you'll want to also fill out `exchange.ts` for the code-token exchange step of OAuth2 [here](https://github.com/Infisical/infisical/blob/main/backend/src/integrations/exchange.ts).

As always, we strongly encourage joining the community Slack to streamline communication, exchange ideas, and seek help from others in the community 😄

**Comment by fruneen** [comment]
Are you planning to integrate with [DigitalOcean App Platform](https://www.digitalocean.com/products/app-platform)?
I think it could be useful in some cases 🙂

**Comment by dangtony98** [comment]
> Are you planning to integrate with [DigitalOcean App Platform](https://www.digitalocean.com/products/app-platform)?
> I think it could be useful in some cases 🙂

Definitely. I’ll have to read up more on the API and how we’d set that up but, assuming that’s possible, I’ll add it to the running integration list 😄

**Comment by chisom5** [comment]
@dangtony98 Windmill integration is complete but the issue is still open.

**Comment by 14traits** [comment]
I hope Secret Syncs for GitLab are coming soon. The legacy integrations are working, but something a bit simpler to use during CI/CD would be excellent. 🍻
